import type { AttackType, GiftRarity, ShakeLevel } from '../types/Gift.ts'

export const rarityPriority: Record<GiftRarity, number> = {
  micro: 1,
  small: 2,
  medium: 3,
  large: 4,
  legendary: 5,
}

export const shakeAmount: Record<ShakeLevel, number> = {
  none: 0,
  small: 0.16,
  medium: 0.3,
  large: 0.52,
  legendary: 0.82,
}

export const attackImpacts: Record<AttackType, number[]> = {
  energy_bullet: [0.74],
  sparkle_shot: [0.7],
  rose: [0.72],
  heart: [0.76],
  fireball: [0.7],
  lightning: [0.48],
  magic: [0.74],
  rocket: [0.82],
  missile: [0.78],
  beam: [0.34],
  fire_blast: [0.48],
  tornado: [0.22, 0.5, 0.8],
  airstrike: [0.42, 0.6, 0.78],
  laser: [0.28],
  thunderstorm: [0.18, 0.36, 0.54, 0.74],
  meteor: [0.7],
  dragon: [0.34, 0.58, 0.84],
  black_hole: [0.74],
  cosmic: [0.42],
  sword: [0.38],
  firestorm: [0.3, 0.48, 0.66, 0.84],
  pulse: [0.82],
  follow_blast: [0.76],
  share_shot: [0.58, 0.72, 0.86],
  ice: [0.66],
}

export const attackBlurbs: Record<AttackType, string> = {
  energy_bullet: 'Small energy shot',
  sparkle_shot: 'Spark burst',
  rose: 'Rose shot',
  heart: 'Heart shot',
  fireball: 'Small fire attack',
  lightning: 'Lightning strike',
  magic: 'Arcane shot',
  rocket: 'Rocket strike',
  missile: 'Missile strike',
  beam: 'Energy beam',
  fire_blast: 'Wide fire blast',
  tornado: 'Spinning hits',
  airstrike: 'Falling strikes',
  laser: 'Focused laser',
  thunderstorm: 'Repeated lightning',
  meteor: 'Meteor strike',
  dragon: 'Dragon sweep',
  black_hole: 'Black hole',
  cosmic: 'Cosmic burst',
  sword: 'Sword slash',
  firestorm: 'Falling fire',
  pulse: 'Team surge',
  follow_blast: 'Follow blast',
  share_shot: 'Share shot',
  ice: 'Ice shard',
}

export const attackHeadlines: Record<AttackType, string> = {
  energy_bullet: 'ENERGY SHOT',
  sparkle_shot: 'SPARK BURST',
  rose: 'ROSE',
  heart: 'HEART',
  fireball: 'FIREBALL',
  lightning: 'LIGHTNING',
  magic: 'ARCANE',
  rocket: 'ROCKET',
  missile: 'MISSILE',
  beam: 'ENERGY BEAM',
  fire_blast: 'FIRE BLAST',
  tornado: 'TORNADO',
  airstrike: 'AIR STRIKE',
  laser: 'LASER',
  thunderstorm: 'THUNDERSTORM',
  meteor: 'METEOR',
  dragon: 'DRAGON',
  black_hole: 'BLACK HOLE',
  cosmic: 'COSMIC BURST',
  sword: 'SWORD STRIKE',
  firestorm: 'FIRE STORM',
  pulse: 'SURGE',
  follow_blast: 'FOLLOW BLAST',
  share_shot: 'SHARE SHOT',
  ice: 'ICE SHARD',
}

export const teamPalette = {
  red: 0xe11d48,
  redHot: 0xffd0dc,
  redDeep: 0x9b1230,
  blue: 0x2d6bff,
  blueIce: 0xd7e6ff,
  blueDeep: 0x143a9a,
  gold: 0xd5dde6,
  ivory: 0xf4f7fb,
  white: 0xffffff,
  ink: 0x07080d,
  cosmic: 0xc7b6ff,
  fire: 0xff7a3c,
}
